# .github/workflows/validate-and-compare-cure.yml
name: Validate & Compare Cure

on:
  push:

jobs:
  validate-and-compare:
    runs-on: ubuntu-latest
    env:
      CURE: ${{ vars.cure }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # ─── Validate JSON formatting ─────────────────────────────────────────────
      - name: Validate JSON format of .vscode/settings.json
        run: |
          test -f .vscode/settings.json \
            || (echo "❌ .vscode/settings.json missing" && exit 1)
          jq -e . .vscode/settings.json > /dev/null \
            || (echo "❌ .vscode/settings.json is not valid JSON" && exit 1)

      - name: Validate JSON format of .vscode/extensions.json
        run: |
          test -f .vscode/extensions.json \
            || (echo "❌ .vscode/extensions.json missing" && exit 1)
          jq -e . .vscode/extensions.json > /dev/null \
            || (echo "❌ .vscode/extensions.json is not valid JSON" && exit 1)

      - name: Validate JSON format of .devcontainer/devcontainer.json
        run: |
          test -f .devcontainer/devcontainer.json \
            || (echo "❌ .devcontainer/devcontainer.json missing" && exit 1)
          jq -e . .devcontainer/devcontainer.json > /dev/null \
            || (echo "❌ .devcontainer/devcontainer.json is not valid JSON" && exit 1)

      # ─── Existing checks ──────────────────────────────────────────────────────
      - name: Ensure LICENSE exists
        run: |
          test -f LICENSE || (echo "❌ LICENSE file missing" && exit 1)

      - name: Ensure 'editor.fontSize' is specified in settings.json
        run: |
          jq -e 'has("editor.fontSize")' .vscode/settings.json \
            || (echo "❌ key 'editor.fontSize' not found in .vscode/settings.json" && exit 1)

      - name: Ensure solution.txt exists
        run: |
          test -f solution.txt || (echo "❌ solution.txt missing" && exit 1)

      - name: Read, trim solution and compare to repo variable
        run: |
          trimmed=$(<solution.txt xargs)
          echo "Trimmed solution.txt → '$trimmed'"
          if [ "$trimmed" != "$CURE" ]; then
            echo "❌ Mismatch: solution.txt ('$trimmed') ≠ vars.cure ('$CURE')" && exit 1
          else
            echo "✅ Match: solution.txt equals vars.cure ('$CURE')"
          fi
